In [18]:
import torch
import numpy as np

In [19]:
mat = [[1,2],
          [3,4],
          [8,9]]
print(mat)
tensor_matrix = torch.Tensor(mat)
print(type(mat))
print(type(tensor_matrix))

[[1, 2], [3, 4], [8, 9]]
<class 'list'>
<class 'torch.Tensor'>


In [20]:
print(tensor_matrix)

tensor([[1., 2.],
        [3., 4.],
        [8., 9.]])


In [21]:
np_mat = np.array(mat)
mat_np_tensor = torch.from_numpy(np_mat)
print(np_mat)
print(mat_np_tensor)

[[1 2]
 [3 4]
 [8 9]]
tensor([[1, 2],
        [3, 4],
        [8, 9]])


In [22]:
tensor_mat_zeros = torch.zeros(2,4)
tensor_mat_random = torch.rand(2,5)
tensor_mat_random_int = torch.randint(2, 10, (2,4))
tensor_mat_ones = torch.ones(2,3)
print(tensor_mat_zeros)
print(tensor_mat_random)
print(tensor_mat_random_int)
print(tensor_mat_ones)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0.6358, 0.3092, 0.1776, 0.1995, 0.2560],
        [0.7650, 0.6372, 0.2796, 0.1189, 0.2275]])
tensor([[8, 5, 4, 2],
        [5, 5, 5, 2]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [23]:
print(tensor_mat_zeros.dtype)
print(tensor_mat_random.dtype)
print(tensor_mat_random_int.dtype)

torch.float32
torch.float32
torch.int64


In [24]:
print(tensor_matrix.device)

cpu


In [25]:
tensor_mat_gpu = tensor_matrix.to('cuda')
print(tensor_mat_gpu.device)
# But the older one reside in cpu and we have only one gpu

cuda:0


In [26]:
# Shape
print(tensor_mat_gpu.shape)

torch.Size([3, 2])


In [27]:
print(tensor_mat_gpu.stride())
print(tensor_mat_gpu.t().stride())

(2, 1)
(1, 2)


In [28]:
!nvidia-smi

Fri Jul  2 03:25:36 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.27       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P0    28W /  70W |   1068MiB / 15109MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [29]:
tensor_new_matrix = torch.ones(4,5)
print(tensor_new_matrix)
print(tensor_new_matrix.shape)
tensor_new_matrix_slice = tensor_new_matrix[:3, :4]
print(tensor_new_matrix_slice)
print(tensor_new_matrix_slice.shape)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
torch.Size([4, 5])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.Size([3, 4])


In [30]:
# Concatenation
rand_input_1 = torch.ones(2,3)
rand_input_2 = torch.zeros(2,5)
print(torch.cat([rand_input_1, rand_input_2], dim = 1))

tensor([[1., 1., 1., 0., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0., 0., 0.]])


In [31]:
rand_input_3 = torch.ones(4,5)
rand_input_4 = torch.rand(2,5)
print(torch.cat([rand_input_3, rand_input_4]))
# print(torch.cat([rand_input_3, rand_input_4], dim = 0))

tensor([[1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [0.6545, 0.1342, 0.4202, 0.7681, 0.5468],
        [0.4009, 0.9706, 0.2912, 0.3155, 0.8664]])


In [32]:
# Multiplication

tensor1 = torch.ones(3,4)
tensor2 = torch.ones(1,4)

''' Two-Types of Multiplication
1. Elementwise,
2. Dot Product like Matrix multiplication.
'''
tensor_ew = tensor1 * tensor2
# tensor_dp = tensor1.matmul(tensor2)
# Upper one will not work beause of dimention problem
tensor3 = torch.ones(4, 5)
tensor_dp = tensor1.matmul(tensor3)
print("tensor element wise multiplication.")
print(tensor_ew)
print("shape of tensor element wise multiplication output", tensor_ew.shape)
print()
print("tensor dot product multiplication.")
print(tensor_dp)
print("shape of tensor dot product multiplication.", tensor_dp.shape)

tensor element wise multiplication.
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
shape of tensor element wise multiplication output torch.Size([3, 4])

tensor dot product multiplication.
tensor([[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]])
shape of tensor dot product multiplication. torch.Size([3, 5])


In [33]:
# In-place Multiplication
inplace_tensor = 9 * torch.ones(2,3) + 1
print(inplace_tensor)
# This will not work inplace_tensor.add(number)

inplace_tensor.add_(8)
inplace_tensor.mul_(10)
inplace_tensor.sub_(90)
inplace_tensor.div_(10)
print(inplace_tensor)

tensor([[10., 10., 10.],
        [10., 10., 10.]])
tensor([[9., 9., 9.],
        [9., 9., 9.]])


In [34]:
# Numpy Bridge
'''
torch supports all operations supported by Numpy. 
Initially, we constructed our tensor from a numpy array. 
To allow easy facilitation and switching between numpy and torch numpy bridge is created to ensure that all changes in numpy.ndarray are reflected in torch.
Tensor and so on. This is done by having a common pointer.
'''

torchtensor = torch.ones(5)
numpyarray = torchtensor.numpy()
print(numpyarray)
torchtensor.sub_(2)
print(numpyarray)

[1. 1. 1. 1. 1.]
[-1. -1. -1. -1. -1.]
